--> Create a new Database
CREATE OR REPLACE DATABASE CUSTOMER_SUPPORT;
USE DATABASE CUSTOMER_SUPPORT;

--> Create a new Schema
CREATE OR REPLACE SCHEMA SUPPORT_ANALYZER;
USE SCHEMA SUPPORT_ANALYZER;

--> Create a table to input the new data
CREATE OR REPLACE TABLE RAW_TICKETS (
    TICKET_ID INT,
    CUSTOMER_NAME STRING,
    CUSTOMER_EMAIL STRING,
    CUSTOMER_AGE INT,
    CUSTOMER_GENDER STRING,
    PRODUCT_PURCHASED STRING,
    DATE_OF_PURCHASE DATE,
    TICKET_TYPE STRING,
    TICKET_SUBJECT STRING,
    TICKET_DESCRIPTION STRING,
    TICKET_STATUS STRING,
    RESOLUTION STRING,
    TICKET_PRIORITY STRING,
    TICKET_CHANNEL STRING,
    FIRST_RESPONSE_TIME TIMESTAMP_NTZ,
    TIME_TO_RESOLUTION TIMESTAMP_NTZ,
    CUSTOMER_SATISFACTION_RATING FLOAT
);

--> Upload the CSV data by directly loading it
--> Verify
SELECT COUNT(*) FROM RAW_TICKETS;   --> This should be 8,469
SELECT * FROM RAW_TICKETS LIMIT 5;

--> Clean TICKET_DESCRIPTION before sentiment analysis
CREATE OR REPLACE TABLE RAW_TICKETS_CLEANED AS
SELECT 
    *,
    REPLACE(TICKET_DESCRIPTION, '{product_purchased}', PRODUCT_PURCHASED) AS TICKET_DESCRIPTION_CLEAN
FROM RAW_TICKETS;

--> Verify to see if the replacement worked
SELECT 
    TICKET_DESCRIPTION,
    TICKET_DESCRIPTION_CLEAN
FROM RAW_TICKETS_CLEANED
LIMIT 5;